{% set name = "pandamesh" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pandamesh-{{ version }}.tar.gz
  sha256: f47316bf1d20c1488a7a78d19ab46e61d97f8d90ef8d6b6c791cc94e5d9d1a19

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - geopandas
    - py-triangle
    - gmsh
    - python-gmsh
    - pooch
    - shapely >=2.0

test:
  imports:
    - pandamesh
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deltares/pandamesh
  summary: From geodataframe to mesh
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://deltares.github.io/pandamesh/
  dev_url: https://github.com/deltares/pandamesh

extra:
  recipe-maintainers:
    - deltares-service-account
    - Huite
    - JoerivanEngelen
    - visr
